local _, ns = ...
local 	Event = CreateFrame("Frame") 
		Event:RegisterEvent("UNIT_HEALTH")
		Event:RegisterEvent("UNIT_POWER_UPDATE")
		Event:RegisterEvent("PLAYER_ENTERING_WORLD",Update) 
		Event:RegisterEvent("PLAYER_REGEN_DISABLED",Update) 
		Event:RegisterEvent("PLAYER_REGEN_ENABLED") 
		Event:RegisterEvent("UNIT_TARGET",Update) 
		Event:RegisterEvent("PLAYER_TARGET_CHANGED")
Event:SetScript("OnEvent",function(self, event, ...) 
		local InCombat, Target = InCombatLockdown(),UnitExists("target")
		if event == "PLAYER_ENTERING_WORLD" and (UnitHealth("player") / UnitHealthMax("player") == 1) then 
		            oUF_Player:EnableMouse(false)
					oUF_Player.Health:SetAlpha(0)
					oUF_Player.Health.backdrop:SetAlpha(0)
					oUF_Player.Health.bg:SetAlpha(0)
                    oUF_Player.Power:SetAlpha(0)
					oUF_Player.Power.backdrop:SetAlpha(0)
					oUF_Player.RaidTargetIndicator:SetAlpha(0)
					oUF_Player.Power.bg:SetAlpha(0)
					oUF_Player.healthValue:SetAlpha(0)
					oUF_Player.nameText:SetAlpha(0)
                    oUF_Player.Highlight:SetAlpha(0)
					oUF_Player.powerText:SetAlpha(0)
                    oUF_Player.RestingIndicator:SetAlpha(0)
					oUF_Player.PhaseIndicator:SetAlpha(0)
                    oUF_Player.LeaderIndicator:SetAlpha(0)
                    oUF_Player.AssistantIndicator:SetAlpha(0)
                    oUF_Player.MasterLooterIndicator:SetAlpha(0)
					oUF_Player.RaidTargetIndicator:SetAlpha(0) 
					oUF_Pet:EnableMouse(false)
					oUF_Pet:SetAlpha(0)
					oUF_Target:SetAlpha(0)
					oUF_Target:EnableMouse(false)
					oUF_ToT:SetAlpha(0)
					oUF_ToT:EnableMouse(false)
		end
end)

Event:SetScript("OnUpdate",function(self, event, ...) 
        local CheckInteractDistance = CheckInteractDistance
        if ( CheckInteractDistance("target", 4) ) then
			oUF_Pet:EnableMouse(false)
			oUF_Pet:SetAlpha(0)
		    oUF_ToT:SetAlpha(0)
			oUF_ToT:EnableMouse(false)
			oUF_Target:SetAlpha(0)
			oUF_Target:EnableMouse(false)
			else
			oUF_Pet:EnableMouse(false)
			oUF_Pet:SetAlpha(0)
		    oUF_ToT:SetAlpha(0)
			oUF_ToT:EnableMouse(false)
			oUF_Target:SetAlpha(0)
			oUF_Target:EnableMouse(false)
		end
end)
